language: python

os:
  - linux

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

matrix:
  include:
    - os: osx
      # Cursory validation on osx, but only with python 3 (to avoid builds taking too long)
      # Workaround for Tavis's current lack of official support for Python on OS X
      # Reference https://github.com/travis-ci/travis-ci/issues/2312
      language: generic
      before_install:
        - brew update
        - brew install libev
        - brew install python3
        - virtualenv env -p python3
        - source env/bin/activate
        - echo Installing RabbitMQ...
        - echo "find / -name rabbitmq-server" $(find / -name rabbitmq-server 2> /dev/null)
        - brew install rabbitmq
        - echo Starting RabbitMQ...
        - export PATH="${PATH}:/usr/local/sbin"
        - sudo rabbitmq-server -detached
    - os: linux
      before_install:
        - echo Installing libev on Linux...
        - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse"
        - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty-updates main restricted universe multiverse"
        - sudo apt-get update -qq
        - sudo apt-get install libev-dev/trusty

install:
  - echo "WHICH python" $(which python)
  - echo "python --version" $(python --version)
  - echo "WHICH pip" $(which pip)
  - echo "pip --version" $(pip --version)
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 ordereddict; fi
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then pip install pyev; fi
  - pip install -r test-requirements.txt
  - pip freeze

services:
  - rabbitmq

script:
  - sudo rabbitmqctl status
  - nosetests

after_success:
  - codecov

deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: crad
  on:
    python: 2.7
    tags: true
    all_branches: true
  password:
    secure: "V/JTU/X9C6uUUVGEAWmWWbmKW7NzVVlC/JWYpo05Ha9c0YV0vX4jOfov2EUAphM0WwkD/MRhz4dq3kCU5+cjHxR3aTSb+sbiElsCpaciaPkyrns+0wT5MCMO29Lpnq2qBLc1ePR1ey5aTWC/VibgFJOL7H/3wyvukL6ZaCnktYk="
